/*
Copyright (c) 2026 José María Micoli
Licensed under {'license_type': 'BSL', 'change_date': '2033-02-17', 'convert_to': 'Apache-2.0'}

You may:
✔ Study
✔ Modify
✔ Use for internal security testing

You may NOT:
✘ Offer as a commercial service
✘ Sell derived competing products
*/

package report

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/JoseMariaMicoli/VaporTrace/pkg/db"
	"github.com/JoseMariaMicoli/VaporTrace/pkg/utils"
	"github.com/pterm/pterm"
)

func GenerateMissionDebrief() {
	utils.TacticalLog("[cyan::b]PHASE 5: REPORT GENERATION STARTED[-:-:-]")

	outputDir := "reports"
	if _, err := os.Stat(outputDir); os.IsNotExist(err) {
		_ = os.Mkdir(outputDir, 0755)
	}

	timestamp := time.Now().Format("20060102_1504")
	reportName := fmt.Sprintf("VAPORTRACE_PEN_TEST_%s.md", timestamp)
	fullPath := filepath.Join(outputDir, reportName)

	f, err := os.Create(fullPath)
	if err != nil {
		utils.TacticalLog(fmt.Sprintf("[red]FileSystem Error:[-] %v", err))
		return
	}
	defer f.Close()

	startTime := "unknown"
	if db.DB != nil {
		_ = db.DB.QueryRow("SELECT value FROM mission_state WHERE key = 'start_time'").Scan(&startTime)
	}

	f.WriteString("# VAPORTRACE TACTICAL DEBRIEF\n")
	f.WriteString(fmt.Sprintf("> **OPERATIONAL STATUS:** COMPLETED\n"))
	f.WriteString(fmt.Sprintf("> **GEN TIME:** %s\n", time.Now().Format("2006-01-02 15:04:05")))
	f.WriteString(fmt.Sprintf("> **START TIME:** %s\n\n", startTime))

	f.WriteString("## 1. EXECUTIVE SUMMARY\n")
	f.WriteString("Automated assessment generated by VaporTrace tactical pipeline.\n\n")

	f.WriteString("## 2. REMEDIATION PRIORITY TRACKER\n")
	writeRemediationTracker(f)

	f.WriteString("\n## 3. METHODOLOGY\n")
	writeMethodology(f)

	f.WriteString("\n## 4. INSTITUTIONAL MEMORY\n")
	writeKnowledgeBaseSection(f)

	f.WriteString("\n---\n")
	f.WriteString("**CONFIDENTIAL // HYDRA-WORM INTEGRITY PROTOCOL**\n")

	pterm.Success.Printf("Tactical report generated: %s\n", fullPath)
	utils.TacticalLog(fmt.Sprintf("[green]Report generated:[-] %s", fullPath))
}

func writeRemediationTracker(f *os.File) {
	f.WriteString("| SEVERITY | CVSS | OWASP | TARGET | DETAILS |\n")
	f.WriteString("| :--- | :--- | :--- | :--- | :--- |\n")

	if db.DB == nil {
		f.WriteString("| N/A | 0.0 | N/A | DB not initialized | No data |\n")
		return
	}

	rows, err := db.DB.Query(`
		SELECT status, cvss_numeric, owasp_id, target, details
		FROM findings
		ORDER BY cvss_numeric DESC, id DESC
	`)
	if err != nil {
		f.WriteString(fmt.Sprintf("| ERROR | 0.0 | DB | query failed | %s |\n", strings.ReplaceAll(err.Error(), "|", "/")))
		return
	}
	defer rows.Close()

	count := 0
	for rows.Next() {
		var status, owasp, target, details string
		var cvss float64
		_ = rows.Scan(&status, &cvss, &owasp, &target, &details)

		safe := strings.ReplaceAll(details, "|", "/")
		f.WriteString(fmt.Sprintf("| %s | %.1f | %s | `%s` | %s |\n", getSeverityIcon(cvss), cvss, owasp, target, safe))
		count++
	}

	if count == 0 {
		f.WriteString("| INFO | 0.0 | N/A | N/A | No findings recorded |\n")
	}
}

func writeMethodology(f *os.File) {
	f.WriteString("- Framework: OWASP API Security Top 10\n")
	f.WriteString("- Severity model: CVSS v3.1\n")
	f.WriteString("- Tactical correlation: MITRE ATT&CK and NIST CSF mapping where available\n")
}

func writeKnowledgeBaseSection(f *os.File) {
	f.WriteString("| TYPE | PAYLOAD | SUCCESS COUNT |\n")
	f.WriteString("| :--- | :--- | :--- |\n")

	if db.DB == nil {
		f.WriteString("| N/A | DB not initialized | 0 |\n")
		return
	}

	rows, err := db.DB.Query("SELECT vuln_type, payload, success_count FROM attack_patterns ORDER BY success_count DESC LIMIT 20")
	if err != nil {
		f.WriteString("| N/A | Knowledge base unavailable | 0 |\n")
		return
	}
	defer rows.Close()

	count := 0
	for rows.Next() {
		var vType, payload string
		var success int
		_ = rows.Scan(&vType, &payload, &success)
		payload = strings.ReplaceAll(payload, "|", "\\|")
		f.WriteString(fmt.Sprintf("| %s | `%s` | %d |\n", vType, payload, success))
		count++
	}

	if count == 0 {
		f.WriteString("| INFO | No learned vectors yet | 0 |\n")
	}
}

func progressBar(count, total int) string {
	if total <= 0 {
		return "░░░░░░░░░░"
	}
	if count < 0 {
		count = 0
	}
	if count > total {
		count = total
	}
	filled := int(float64(count) / float64(total) * 10.0)
	return strings.Repeat("█", filled) + strings.Repeat("░", 10-filled)
}

func getSeverityIcon(score float64) string {
	if score >= 9.0 {
		return "CRITICAL"
	}
	if score >= 7.0 {
		return "HIGH"
	}
	if score >= 4.0 {
		return "MEDIUM"
	}
	return "LOW"
}

func GetCurrentReportMarkdown() string {
	var sb strings.Builder
	sb.WriteString("# VAPORTRACE MISSION DEBRIEF\n")
	sb.WriteString("## 3. TECHNICAL FINDINGS\n")
	sb.WriteString("| SEVERITY | CVSS | OWASP | TARGET | DETAILS |\n")
	sb.WriteString("| :--- | :--- | :--- | :--- | :--- |\n")

	if db.DB == nil {
		sb.WriteString("| INFO | 0.0 | N/A | DB not initialized | No data |\n")
		return sb.String()
	}

	rows, err := db.DB.Query(`
		SELECT status, cvss_numeric, owasp_id, target, details
		FROM findings
		ORDER BY cvss_numeric DESC, id DESC
	`)
	if err != nil {
		sb.WriteString(fmt.Sprintf("| ERROR | 0.0 | DB | query failed | %s |\n", strings.ReplaceAll(err.Error(), "|", "/")))
		return sb.String()
	}
	defer rows.Close()

	count := 0
	for rows.Next() {
		var status, owasp, target, details string
		var cvss float64
		_ = rows.Scan(&status, &cvss, &owasp, &target, &details)
		safe := strings.ReplaceAll(details, "|", "/")
		sb.WriteString(fmt.Sprintf("| %s | %.1f | %s | `%s` | %s |\n", getSeverityIcon(cvss), cvss, owasp, target, safe))
		count++
	}

	if count == 0 {
		sb.WriteString("| INFO | 0.0 | N/A | N/A | No findings recorded |\n")
	}

	return sb.String()
}
